=== martimdfneves/ECT/4 ano/EDC/aula 2/curso.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="curso" type="cursoType"/>
  <xs:complexType name="areasType">
    <xs:sequence>
      <xs:element type="xs:string" name="area"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="directorType">
    <xs:sequence>
      <xs:element type="xs:string" name="titulo"/>
      <xs:element type="xs:string" name="nome"/>
      <xs:element type="xs:string" name="email"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="departamentoType">
    <xs:sequence>
      <xs:element type="xs:string" name="nome"/>
      <xs:element type="xs:string" name="url"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="departamentosType">
    <xs:sequence>
      <xs:element type="departamentoType" name="departamento"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="mediasType">
    <xs:sequence>
      <xs:element type="xs:string" name="fase1"/>
      <xs:element type="xs:string" name="fase2"/>
      <xs:element type="xs:string" name="fase3"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="vagasType">
    <xs:sequence>
      <xs:element type="xs:string" name="fase1"/>
      <xs:element type="xs:string" name="fase2"/>
      <xs:element type="xs:string" name="fase3"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="m23Type">
    <xs:sequence>
      <xs:element type="xs:string" name="provas"/>
      <xs:element type="xs:string" name="vagas"/>
      <xs:element type="xs:string" name="urlinfo"/>
      <xs:element type="xs:string" name="observacoes"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="faseType">
    <xs:sequence>
      <xs:element name="numero">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="1"/>
            <xs:enumeration value="2"/>
            <xs:enumeration value="3"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="periodo">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="14/04/2020 a 24/04/2020"/>
            <xs:enumeration value="20/07/2020 a 21/08/2020"/>
            <xs:enumeration value="14/10/2020 to 18/10/2020"/>
            <xs:enumeration value="14/10/2020 a 18/10/2020"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="edital">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="https://acesso.ua.pt/upload/editais/e_5015.pdf"/>
            <xs:enumeration value="https://acesso.ua.pt/upload/editais/e_5233.pdf"/>
            <xs:enumeration value="https://acesso.ua.pt/upload/editais/e_5017.pdf"/>
            <xs:enumeration value="https://acesso.ua.pt/upload/editais/e_5237.pdf"/>
            <xs:enumeration value="https://acesso.ua.pt/upload/editais/e_5019.pdf"/>
            <xs:enumeration value="https://acesso.ua.pt/upload/editais/e_5173.pdf"/>
            <xs:enumeration value="https://acesso.ua.pt/upload/editais/e_5460.pdf"/>
            <xs:enumeration value="https://acesso.ua.pt/upload/editais/e_5461.pdf"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="ata">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="https://acesso.ua.pt/upload/atas/a_5015.pdf"/>
            <xs:enumeration value="https://acesso.ua.pt/upload/atas/a_5233.pdf"/>
            <xs:enumeration value="https://acesso.ua.pt/upload/atas/a_5017.pdf"/>
            <xs:enumeration value="https://acesso.ua.pt/upload/atas/a_5237.pdf"/>
            <xs:enumeration value="https://acesso.ua.pt/upload/atas/a_5019.pdf"/>
            <xs:enumeration value="https://acesso.ua.pt/upload/atas/a_5173.pdf"/>
            <xs:enumeration value="https://acesso.ua.pt/upload/atas/a_5460.pdf"/>
            <xs:enumeration value="https://acesso.ua.pt/upload/atas/a_5461.pdf"/>
            <xs:enumeration value=""/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="datainicio">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="2020-03-23"/>
            <xs:enumeration value="2020-07-03"/>
            <xs:enumeration value="2020-07-02"/>
            <xs:enumeration value="2020-10-13"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="xs:string" name="datafim"/>
      <xs:element type="xs:string" name="vagas"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="fasesType">
    <xs:sequence>
      <xs:element type="faseType" name="fase" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="posgraduacoesType">
    <xs:sequence>
      <xs:element type="xs:string" name="corpo_docente"/>
      <xs:element type="xs:string" name="destinatarios"/>
      <xs:element type="xs:string" name="vagas"/>
      <xs:element type="xs:string" name="vagas_obs"/>
      <xs:element type="xs:string" name="urlmobilidade"/>
      <xs:element type="xs:string" name="ano_info"/>
      <xs:element type="fasesType" name="fases"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="a3esType">
    <xs:sequence>
      <xs:element type="xs:string" name="situacao"/>
      <xs:element type="xs:string" name="numero"/>
      <xs:element type="xs:string" name="despacho"/>
      <xs:element type="xs:string" name="data"/>
      <xs:element type="xs:string" name="deliberacao"/>
      <xs:element type="xs:string" name="dr"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="acreditacaoType">
    <xs:sequence minOccurs="0">
      <xs:element type="xs:string" name="nome"/>
      <xs:element type="xs:string" name="texto"/>
      <xs:element type="xs:string" name="imagem"/>
      <xs:element type="xs:string" name="url"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="acreditacoesType">
    <xs:sequence minOccurs="0">
      <xs:element type="acreditacaoType" name="acreditacao"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="cursoType">
    <xs:sequence>
      <xs:element type="xs:string" name="guid"/>
      <xs:element type="xs:string" name="nome"/>
      <xs:element type="xs:string" name="nota"/>
      <xs:element type="xs:string" name="imagem"/>
      <xs:element type="xs:string" name="codigo"/>
      <xs:element type="xs:string" name="grau"/>
      <xs:element type="xs:string" name="grauid"/>
      <xs:element type="xs:string" name="ciclo"/>
      <xs:element type="xs:string" name="duracao"/>
      <xs:element type="xs:string" name="ano_inicio"/>
      <xs:element type="xs:string" name="regime"/>
      <xs:element type="xs:string" name="horario"/>
      <xs:element type="xs:string" name="propinas"/>
      <xs:element type="xs:string" name="subsistema"/>
      <xs:element type="areasType" name="areas"/>
      <xs:element type="directorType" name="director"/>
      <xs:element type="departamentosType" name="departamentos"/>
      <xs:element type="mediasType" name="medias"/>
      <xs:element type="vagasType" name="vagas"/>
      <xs:element type="xs:string" name="abrecandidaturas"/>
      <xs:element type="xs:string" name="provas"/>
      <xs:element type="xs:string" name="ano_info"/>
      <xs:element type="xs:string" name="saidas_profissionais"/>
      <xs:element type="xs:string" name="objectivos"/>
      <xs:element type="xs:string" name="observacoes"/>
      <xs:element type="xs:string" name="testemunho"/>
      <xs:element type="xs:string" name="pre_requisitos"/>
      <xs:element type="xs:string" name="local"/>
      <xs:element type="xs:string" name="urlmaisinfo"/>
      <xs:element type="xs:string" name="urlcandidaturas"/>
      <xs:element type="xs:string" name="urlmobilidade"/>
      <xs:element type="m23Type" name="m23"/>
      <xs:element type="posgraduacoesType" name="posgraduacoes"/>
      <xs:element type="a3esType" name="a3es"/>
      <xs:element type="acreditacoesType" name="acreditacoes"/>
      <xs:element type="xs:string" name="ultimaalteracao"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== martimdfneves/ECT/4 ano/EDC/aula 2/mect.xml
<?xml version="1.0" encoding="utf-8"?>
<curso xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="curso.xsd">
	<guid>23</guid>
	<nome><![CDATA[Engenharia de Computadores e Telemática]]></nome>
	<nota></nota>
	<imagem><![CDATA[https://acesso.ua.pt/upload/imagens/c_23.png]]></imagem>
	<codigo>0300/9361</codigo>
	<grau><![CDATA[Mestrado Integrado]]></grau>
	<grauid><![CDATA[6]]></grauid>
	<ciclo>1</ciclo>
	<duracao>5 anos letivos / 10 semestres (300 créditos ECTS)</duracao>
	<ano_inicio>2006/2007</ano_inicio>
	<regime><![CDATA[Diurno / laboral]]></regime>
	<horario></horario>
	<propinas><![CDATA[697€/ano (ingresso no 1º ano) / 1000€/ano (ingresso no 4º ano)]]></propinas>
	<subsistema><![CDATA[Universitário]]></subsistema>
	<areas>
		<area><![CDATA[Informática]]></area>
	</areas>
	<director>
		<titulo>Prof. Doutor</titulo>
		<nome>Joaquim João Estrela Ribeiro Silvestre Madeira</nome>
		<email>jmadeira@ua.pt</email>
	</director>
	<departamentos>
		<departamento>
			<nome>Departamento de Eletrónica, Telecomunicações e Informática</nome>
			<url>http://www.ua.pt/deti</url>
		</departamento>
	</departamentos>
	<medias>
		<fase1>149</fase1>
		<fase2>0</fase2>
		<fase3>0</fase3>
	</medias>
	<vagas>
		<fase1>85</fase1>
		<fase2>0</fase2>
		<fase3>0</fase3>
	</vagas>
	<abrecandidaturas>true</abrecandidaturas>
	<provas><![CDATA[Um dos seguintes conjuntos:<br />
19 Matemática A<br />
      ou<br />
02 Biologia e Geologia<br />
19 Matemática A<br />
      ou<br />
07 Física e Química<br />
19 Matemática A
<br /><br /><strong>O cálculo da nota de acesso considera:</strong><ul><li>50% da nota do ensino secundário</li><li>50% da nota da prova de ingresso</li></ul>]]></provas>
	<ano_info><![CDATA[2020/2021]]></ano_info>
	<saidas_profissionais><![CDATA[<p>Os Mestres em Engenharia de Computadores e Telem&aacute;tica est&atilde;o preparados para intervir nas novas &aacute;reas que integram as tecnologias de informa&ccedil;&atilde;o, a ci&ecirc;ncia e engenharia de computadores e as telecomunica&ccedil;&otilde;es.</p>
<p>Assim, poder&atilde;o desempenhar fun&ccedil;&otilde;es em organiza&ccedil;&otilde;es p&uacute;blicas e privadas que realizem projetos de investiga&ccedil;&atilde;o, desenvolvimento e integra&ccedil;&atilde;o/utiliza&ccedil;&atilde;o de novas tecnologias da informa&ccedil;&atilde;o e comunica&ccedil;&atilde;o para a cria&ccedil;&atilde;o de novos servi&ccedil;os ligados &agrave; economia digital, de sistemas de informa&ccedil;&atilde;o ou para o projeto de equipamento.</p>
<p>Ser&atilde;o assim respons&aacute;veis tecnicamente por projetar, adaptar ou gerir solu&ccedil;&otilde;es, sistemas e redes inform&aacute;ticas complexas. As sa&iacute;das profissionais s&atilde;o m&uacute;ltiplas desde o setor dos servi&ccedil;os - onde &eacute; de real&ccedil;ar a banca, os seguros, o turismo, a cultura, o multim&eacute;dia - ao setor industrial, passando pela Administra&ccedil;&atilde;o P&uacute;blica Central, Local e Regional.</p>]]></saidas_profissionais>
	<objectivos><![CDATA[<p>&Eacute; indiscut&iacute;vel, hoje, que a independ&ecirc;ncia e o desenvolvimento de um pa&iacute;s passa grandemente pela capacidade de se autonomizar do ponto de vista tecnol&oacute;gico. Mat&eacute;rias como os Computadores, Telem&aacute;tica e Inform&aacute;tica s&atilde;o inevitavelmente de import&acirc;ncia primordial, quer pela sua relev&acirc;ncia como elementos coadjuvantes de outras t&eacute;cnicas, quer pela sua interven&ccedil;&atilde;o direta em sistemas que condicionam cada vez mais a vida das pessoas. Computadores, redes de telecomunica&ccedil;&otilde;es, sistemas embutidos, telem&oacute;veis s&atilde;o alguns dos exemplos importantes.</p>
<p>O curso de Mestrado Integrado em Computadores e Telem&aacute;tica da Universidade de Aveiro (MIECT-UA) tem por finalidade fornecer uma forma&ccedil;&atilde;o s&oacute;lida em ci&ecirc;ncias de base e de espetro largo nas &aacute;reas das tecnologias da computa&ccedil;&atilde;o, informa&ccedil;&atilde;o e das telecomunica&ccedil;&otilde;es, as quais t&ecirc;m vindo a assumir um papel dominante no setor industrial e o principal motor de desenvolvimento nas economias avan&ccedil;adas.</p>
<p>A tradi&ccedil;&atilde;o da Universidade de Aveiro neste dom&iacute;nio &eacute; forte. Aqui nasceu, por exemplo, o Servi&ccedil;o de Apontadores Portugueses (SAPO). A escolha de Aveiro como primeira Cidade Digital reflete tamb&eacute;m o capital de conhecimentos adquiridos nesta &aacute;rea, n&atilde;o s&oacute; pela Universidade como tamb&eacute;m por outras institui&ccedil;&otilde;es da cidade. Nos pr&oacute;ximos anos, os projetos que, no &acirc;mbito do programa Cidades Digitais, aqui se forem desenvolvendo dar&atilde;o, por certo, um excelente enquadramento &agrave; forma&ccedil;&atilde;o fornecida pela Mestrado Integrado em Computadores e Telem&aacute;tica.</p>
<p>A responsabilidade por esta licenciatura &eacute; assumida pelo Departamento de Eletr&oacute;nica, Telecomunica&ccedil;&otilde;es e Inform&aacute;tica da Universidade de Aveiro. Fundado em 1974, este departamento &eacute; detentor de um prestigiante historial nas &aacute;reas dos computadores e das telecomunica&ccedil;&otilde;es. O curr&iacute;culo do curso recorre, pois, &agrave;s compet&ecirc;ncias adquiridas para construir um perfil que fornece uma s&oacute;lida forma&ccedil;&atilde;o geral nas &aacute;reas da Engenharia Inform&aacute;tica.</p>]]></objectivos>
	<observacoes><![CDATA[É conferido o grau de licenciado em Ciências da Engenharia de Computadores e Telemática aos alunos que tenham realizado os 180 ECTS correspondentes aos primeiros seis semestres curriculares de trabalho.]]></observacoes>
	<testemunho></testemunho>
	<pre_requisitos></pre_requisitos>
	<local><![CDATA[Campus Universitário de Santiago, Aveiro]]></local>
	<urlmaisinfo></urlmaisinfo>
	<urlcandidaturas></urlcandidaturas>
	<urlmobilidade></urlmobilidade>
	<m23>
		<provas><![CDATA[matemática
<a href="https://www.ua.pt/pt/exames-entrevistas" target=_blank>programa</a>]]></provas>
		<vagas></vagas>
		<urlinfo><![CDATA[http://www.ua.pt/pt/m23]]></urlinfo>
		<observacoes></observacoes>
	</m23>
	<posgraduacoes>
		<corpo_docente></corpo_docente>
		<destinatarios></destinatarios>
		<vagas></vagas>
		<vagas_obs></vagas_obs>
		<urlmobilidade></urlmobilidade>
		<ano_info></ano_info>
		<fases>
			
			<fase>
				<numero><![CDATA[1]]></numero>
				<periodo><![CDATA[14/04/2020 a 24/04/2020]]></periodo>
				<edital><![CDATA[https://acesso.ua.pt/upload/editais/e_5015.pdf]]></edital>
				<ata><![CDATA[https://acesso.ua.pt/upload/atas/a_5015.pdf]]></ata>
				<datainicio><![CDATA[2020-03-23]]></datainicio>
				<datafim><![CDATA[2021-02-28]]></datafim>
				<vagas><![CDATA[25]]></vagas>
			</fase>
			
			<fase>
				<numero><![CDATA[2]]></numero>
				<periodo><![CDATA[20/07/2020 a 21/08/2020]]></periodo>
				<edital><![CDATA[https://acesso.ua.pt/upload/editais/e_5233.pdf]]></edital>
				<ata><![CDATA[https://acesso.ua.pt/upload/atas/a_5233.pdf]]></ata>
				<datainicio><![CDATA[2020-07-03]]></datainicio>
				<datafim><![CDATA[2021-02-28]]></datafim>
				<vagas><![CDATA[25]]></vagas>
			</fase>
			
		</fases>
	</posgraduacoes>
	<a3es>
		
		<situacao><![CDATA[acreditado]]></situacao>
		<numero><![CDATA[R/B -AD -660/2006]]></numero>
		<despacho><![CDATA[Declaracao_Retificacao_538_2013 ao Despacho n.º 4273/2013]]></despacho>
		<data><![CDATA[02/07/2014]]></data>
		<deliberacao><![CDATA[http://www.a3es.pt/pt/resultados-acreditacao/engenharia-de-computadores-e-telematica-0]]></deliberacao>
		<dr><![CDATA[Diário da República, 2.ª série — N.º 85 — 3 de maio de 2013]]></dr>
		
	</a3es>
	<acreditacoes>
	
		<acreditacao>
			<nome><![CDATA[selo de qualidade EUR-ACE]]></nome>
			<texto></texto>
			<imagem><![CDATA[http://acesso.ua.pt/images/cert_eurace.png]]></imagem>
			<url><![CDATA[http://www.enaee.eu/eur-ace-system]]></url>
		</acreditacao>
	
	</acreditacoes>
	<ultimaalteracao><![CDATA[15/10/2020 10:29:00]]></ultimaalteracao>
</curso>

=== martimdfneves/ECT/4 ano/1 semestre/EDC/aula 2/meet.xml
<?xml version="1.0" encoding="utf-8"?>
<curso xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="curso.xsd">
    <guid>27</guid>
    <nome><![CDATA[Engenharia Eletrónica e Telecomunicações]]></nome>
    <nota><![CDATA[marca EUR-ACE]]></nota>
    <imagem><![CDATA[http://acesso.ua.pt/upload/imagens/c_27.jpg]]></imagem>
    <codigo>0300/9365</codigo>
    <grau><![CDATA[Mestrado Integrado]]></grau>
    <grauid><![CDATA[6]]></grauid>
    <ciclo>1</ciclo>
    <duracao>5 anos letivos / 10 semestres (300 créditos ECTS)</duracao>
    <ano_inicio>2006/2007</ano_inicio>
    <regime><![CDATA[Diurno / laboral]]></regime>
    <horario></horario>
    <propinas><![CDATA[697€/ano (ingresso no 1º ano) / 1000€/ano (ingresso no 4º ano)]]></propinas>
    <subsistema><![CDATA[Universitário]]></subsistema>
    <areas>
        <area><![CDATA[Eletrotecnia]]></area>
    </areas>
    <director>
        <titulo>Prof. Doutor</titulo>
        <nome>António José Ribeiro Neves</nome>
        <email>an@ua.pt</email>
    </director>
    <departamentos>
        <departamento>
            <nome>Departamento de Eletrónica, Telecomunicações e Informática</nome>
            <url>http://www.ua.pt/deti</url>
        </departamento>
    </departamentos>
    <medias>
        <fase1>118,8</fase1>
        <fase2>0</fase2>
        <fase3>0</fase3>
    </medias>
    <vagas>
        <fase1>83</fase1>
        <fase2>2</fase2>
        <fase3>0</fase3>
    </vagas>
    <abrecandidaturas>true</abrecandidaturas>
    <provas><![CDATA[07 Física e Química <br />19 Matemática A
<br /><br /><strong>O cálculo da nota de acesso considera:</strong><ul><li>50% da nota do ensino secundário</li><li>50% da nota da prova de ingresso</li></ul>]]></provas>
    <ano_info><![CDATA[2020/2021]]></ano_info>
    <saidas_profissionais><![CDATA[<p>Os Mestres em Engenharia Eletr&oacute;nica e Telecomunica&ccedil;&otilde;es estar&atilde;o habilitados a desempenhar fun&ccedil;&otilde;es de quadros superiores em empresas p&uacute;blicas e privadas, cuja atividade envolva direta ou indiretamente a utiliza&ccedil;&atilde;o, gest&atilde;o e projeto de Sistemas Eletr&oacute;nicos (anal&oacute;gicos e digitais), Computadores, Telecomunica&ccedil;&otilde;es, Instrumenta&ccedil;&atilde;o, Automa&ccedil;&atilde;o e Controlo e An&aacute;lise e Processamento de Sinal.</p>
<p>As sa&iacute;das profissionais s&atilde;o m&uacute;ltiplas, situando-se nos operadores de telecomunica&ccedil;&otilde;es, nas empresas de produ&ccedil;&atilde;o e manuten&ccedil;&atilde;o de software, nos gabinetes de estudo e projetistas, nas empresas de consultoria, no setor financeiro, nos fabricantes e distribuidores de equipamento el&eacute;trico e eletr&oacute;nico, em todo o tipo de empresas industriais e de servi&ccedil;os e ainda em muitos servi&ccedil;os p&uacute;blicos.<br /><br /></p>]]></saidas_profissionais>
    <objectivos><![CDATA[<p>O Mestrado Integrado em Engenharia Eletr&oacute;nica e Telecomunica&ccedil;&otilde;es<br />tem como objetivo dar uma forma&ccedil;&atilde;o s&oacute;lida em ci&ecirc;ncias de base, e de espetro largo ao n&iacute;vel das ci&ecirc;ncias da especialidade, formando t&eacute;cnicos a n&iacute;vel superior, capazes de desempenhar fun&ccedil;&otilde;es de planeamento e projeto nos dom&iacute;nios dos Sistemas Eletr&oacute;nicos (anal&oacute;gicos e digitais), Computadores, Telecomunica&ccedil;&otilde;es, Instrumenta&ccedil;&atilde;o, Automa&ccedil;&atilde;o e Controlo e An&aacute;lise e Processamento de Sinal. Atrav&eacute;s de uma forma&ccedil;&atilde;o s&oacute;lida em ci&ecirc;ncias de base, pretende fornecer aos seus diplomados uma mais f&aacute;cil e eficaz adapta&ccedil;&atilde;o &agrave; r&aacute;pida evolu&ccedil;&atilde;o tecnol&oacute;gica. Atrav&eacute;s de uma forma&ccedil;&atilde;o de espetro largo ao n&iacute;vel das ci&ecirc;ncias da especialidade, procura dotar os seus diplomados de uma maior flexibilidade e vis&atilde;o de conjunto sobre a &aacute;rea profissional a que se destina. Qualquer destes objetivos &eacute;, em nossa opini&atilde;o, determinante para o desenvolvimento tecnol&oacute;gico sustentado do pa&iacute;s.</p>
<p>De facto, a forma&ccedil;&atilde;o oferecida por este Mestrado Integrado em Engenharia Eletr&oacute;nica e Telecomunica&ccedil;&otilde;es &eacute; orientada tanto para as exig&ecirc;ncias atuais da ind&uacute;stria nacional, como para dom&iacute;nios tecnol&oacute;gicos mais avan&ccedil;ados que vir&atilde;o a ter reflexos no pa&iacute;s a m&eacute;dio e longo prazo. Muitos dos atuais Engenheiros de Eletr&oacute;nica e Telecomunica&ccedil;&otilde;es formados pela Universidade de Aveiro ocupam hoje posi&ccedil;&otilde;es de destaque, n&atilde;o s&oacute; no mundo empresarial, como tamb&eacute;m no dom&iacute;nio do ensino e da investiga&ccedil;&atilde;o. A recetividade do mercado de trabalho tem sido total, chegando mesmo a verificar-se a contrata&ccedil;&atilde;o de muitos alunos antes de conclu&iacute;rem o curso. A cria&ccedil;&atilde;o da sua pr&oacute;pria empresa tem sido igualmente uma op&ccedil;&atilde;o para muitos desses Engenheiros.</p>]]></objectivos>
    <observacoes>
        <![CDATA[É conferido o grau de licenciado em Ciências da Engenharia Eletrónica e Telecomunicações aos alunos que tenham realizado os 180 ECTS correspondentes aos primeiros seis semestres curriculares de trabalho.]]></observacoes>
    <testemunho></testemunho>
    <pre_requisitos></pre_requisitos>
    <local><![CDATA[Campus Universitário de Santiago, Aveiro]]></local>
    <urlmaisinfo></urlmaisinfo>
    <urlcandidaturas></urlcandidaturas>
    <urlmobilidade></urlmobilidade>
    <m23>
        <provas>
            <![CDATA[matemática E física <a href="https://www.ua.pt/pt/exames-entrevistas" target=_blank>programa</a>]]></provas>
        <vagas></vagas>
        <urlinfo><![CDATA[http://www.ua.pt/pt/m23]]></urlinfo>
        <observacoes></observacoes>
    </m23>
    <posgraduacoes>
        <corpo_docente></corpo_docente>
        <destinatarios></destinatarios>
        <vagas></vagas>
        <vagas_obs></vagas_obs>
        <urlmobilidade></urlmobilidade>
        <ano_info></ano_info>
        <fases>

            <fase>
                <numero><![CDATA[1]]></numero>
                <periodo><![CDATA[14/04/2020 a 24/04/2020]]></periodo>
                <edital><![CDATA[https://acesso.ua.pt/upload/editais/e_5017.pdf]]></edital>
                <ata><![CDATA[https://acesso.ua.pt/upload/atas/a_5017.pdf]]></ata>
                <datainicio><![CDATA[2020-03-23]]></datainicio>
                <datafim><![CDATA[2021-02-28]]></datafim>
                <vagas><![CDATA[35]]></vagas>
            </fase>

            <fase>
                <numero><![CDATA[2]]></numero>
                <periodo><![CDATA[20/07/2020 a 21/08/2020]]></periodo>
                <edital><![CDATA[https://acesso.ua.pt/upload/editais/e_5237.pdf]]></edital>
                <ata><![CDATA[https://acesso.ua.pt/upload/atas/a_5237.pdf]]></ata>
                <datainicio><![CDATA[2020-07-03]]></datainicio>
                <datafim><![CDATA[2021-02-28]]></datafim>
                <vagas><![CDATA[35]]></vagas>
            </fase>

        </fases>
    </posgraduacoes>
    <a3es>

        <situacao><![CDATA[acreditado]]></situacao>
        <numero><![CDATA[R/A -Cr 1/2018]]></numero>
        <despacho><![CDATA[Aviso n.º 7108_2018]]></despacho>
        <data><![CDATA[11/01/2018]]></data>
        <deliberacao>
            <![CDATA[http://a3es.pt/pt/resultados-acreditacao/engenharia-electronica-e-telecomunicacoes-6]]></deliberacao>
        <dr><![CDATA[Diário da República, 2.ª série — N.º 101 — 25 de maio de 2018]]></dr>

    </a3es>
    <acreditacoes>

        <acreditacao>
            <nome><![CDATA[selo de qualidade EUR-ACE]]></nome>
            <texto></texto>
            <imagem><![CDATA[http://acesso.ua.pt/images/cert_eurace.png]]></imagem>
            <url><![CDATA[http://www.enaee.eu/eur-ace-system]]></url>
        </acreditacao>

    </acreditacoes>
    <ultimaalteracao><![CDATA[15/10/2020 10:30:00]]></ultimaalteracao>
</curso>

=== martimdfneves/ECT/4 ano/1 semestre/EDC/aula 2/mei.xml
<?xml version="1.0" encoding="utf-8"?>
<curso xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="curso.xsd">
    <guid>417</guid>
    <nome><![CDATA[Engenharia Informática]]></nome>
    <nota></nota>
    <imagem><![CDATA[https://acesso.ua.pt/upload/imagens/c_417.png]]></imagem>
    <codigo>9263</codigo>
    <grau><![CDATA[Mestrado]]></grau>
    <grauid><![CDATA[4]]></grauid>
    <ciclo>2</ciclo>
    <duracao>2 anos</duracao>
    <ano_inicio>2016/2017</ano_inicio>
    <regime><![CDATA[Diurno / laboral]]></regime>
    <horario></horario>
    <propinas><![CDATA[1 000,00€/ano]]></propinas>
    <subsistema><![CDATA[Universitário]]></subsistema>
    <areas>
        <area><![CDATA[Informática]]></area>
    </areas>
    <director>
        <titulo>Prof. Doutor</titulo>
        <nome>José Luis Guimarães Oliveira</nome>
        <email>jlo@ua.pt</email>
    </director>
    <departamentos>
        <departamento>
            <nome>Departamento de Eletrónica, Telecomunicações e Informática</nome>
            <url>http://www.ua.pt/deti</url>
        </departamento>
    </departamentos>
    <medias>
        <fase1>0</fase1>
        <fase2>0</fase2>
        <fase3>0</fase3>
    </medias>
    <vagas>
        <fase1>0</fase1>
        <fase2>0</fase2>
        <fase3>0</fase3>
    </vagas>
    <abrecandidaturas>true</abrecandidaturas>
    <provas></provas>
    <ano_info><![CDATA[2020/2021]]></ano_info>
    <saidas_profissionais></saidas_profissionais>
    <objectivos><![CDATA[<p>Os objetivos do MEI est&atilde;o alinhados com esta estrat&eacute;gia e com as necessidades do mercado, procurando-se:</p>
<ul>
<li>Dotar o tecido empresarial da regi&atilde;o, nacional e internacional de quadros superiores habilitados;&nbsp;</li>
<li>Fomentar uma forma&ccedil;&atilde;o avan&ccedil;ada centrada em inova&ccedil;&atilde;o, desenvolvimento e investiga&ccedil;&atilde;o em engenharia inform&aacute;tica;</li>
</ul>]]></objectivos>
    <observacoes></observacoes>
    <testemunho></testemunho>
    <pre_requisitos></pre_requisitos>
    <local><![CDATA[Campus Universitário de Santiago, Aveiro]]></local>
    <urlmaisinfo></urlmaisinfo>
    <urlcandidaturas></urlcandidaturas>
    <urlmobilidade></urlmobilidade>
    <m23>
        <provas></provas>
        <vagas></vagas>
        <urlinfo></urlinfo>
        <observacoes></observacoes>
    </m23>
    <posgraduacoes>
        <corpo_docente></corpo_docente>
        <destinatarios></destinatarios>
        <vagas><![CDATA[50]]></vagas>
        <vagas_obs></vagas_obs>
        <urlmobilidade></urlmobilidade>
        <ano_info><![CDATA[2020/2021]]></ano_info>
        <fases>

            <fase>
                <numero><![CDATA[1]]></numero>
                <periodo><![CDATA[14/04/2020 a 24/04/2020]]></periodo>
                <edital><![CDATA[https://acesso.ua.pt/upload/editais/e_5019.pdf]]></edital>
                <ata><![CDATA[https://acesso.ua.pt/upload/atas/a_5019.pdf]]></ata>
                <datainicio><![CDATA[2020-03-23]]></datainicio>
                <datafim><![CDATA[2021-02-28]]></datafim>
                <vagas><![CDATA[10]]></vagas>
            </fase>

            <fase>
                <numero><![CDATA[2]]></numero>
                <periodo><![CDATA[20/07/2020 a 21/08/2020]]></periodo>
                <edital><![CDATA[https://acesso.ua.pt/upload/editais/e_5173.pdf]]></edital>
                <ata><![CDATA[https://acesso.ua.pt/upload/atas/a_5173.pdf]]></ata>
                <datainicio><![CDATA[2020-07-02]]></datainicio>
                <datafim><![CDATA[2021-02-28]]></datafim>
                <vagas><![CDATA[40]]></vagas>
            </fase>

            <fase>
                <numero><![CDATA[3]]></numero>
                <periodo><![CDATA[14/10/2020 a 18/10/2020]]></periodo>
                <edital><![CDATA[https://acesso.ua.pt/upload/editais/e_5460.pdf]]></edital>
                <ata><![CDATA[https://acesso.ua.pt/upload/atas/a_5460.pdf]]></ata>
                <datainicio><![CDATA[2020-10-13]]></datainicio>
                <datafim><![CDATA[2021-02-28]]></datafim>
                <vagas><![CDATA[12]]></vagas>
            </fase>

            <fase>
                <numero><![CDATA[3]]></numero>
                <periodo><![CDATA[14/10/2020 to 18/10/2020]]></periodo>
                <edital><![CDATA[https://acesso.ua.pt/upload/editais/e_5461.pdf]]></edital>
                <ata></ata>
                <datainicio><![CDATA[2020-10-13]]></datainicio>
                <datafim><![CDATA[2021-02-28]]></datafim>
                <vagas><![CDATA[12]]></vagas>
            </fase>

        </fases>
    </posgraduacoes>
    <a3es>

        <situacao><![CDATA[acreditado]]></situacao>
        <numero><![CDATA[R/A-Cr 20/2016/AL01]]></numero>
        <despacho><![CDATA[Aviso_nº_4782_2016]]></despacho>
        <data><![CDATA[24/02/2016]]></data>
        <deliberacao><![CDATA[http://a3es.pt/pt/resultados-acreditacao/engenharia-informatica-89]]></deliberacao>
        <dr><![CDATA[Diário da República, 2.ª série — N.º 70 — 11 de abril de 2016]]></dr>

    </a3es>
    <acreditacoes>

    </acreditacoes>
    <ultimaalteracao><![CDATA[10/09/2020 10:51:00]]></ultimaalteracao>
</curso>
